# @package _global_
model:
  max_rings: 2
  max_ring_length: 5
  constraints:
    - type: ring_count_at_most
      max_rings: ${model.max_rings}
    - type: ring_length_at_most
      max_ring_length: ${model.max_ring_length}
  use_projection: true
general:
  sampling_output_dir: samples/${general.name}/at_most_count_2_length_5/seed_${train.seed}
