# @package _global_
model:
  min_rings: 1
  min_ring_length: 4
  constraints:
    - type: ring_count_at_least
      min_rings: ${model.min_rings}
    - type: ring_length_at_least
      min_ring_length: ${model.min_ring_length}
  use_projection: true
general:
  sampling_output_dir: samples/${general.name}/count_1_length_4/seed_${train.seed}
