# @package _global_
model:
  min_rings: 2
  constraints:
    - type: ring_count_at_least
      min_rings: ${model.min_rings}
  use_projection: true
general:
  sampling_output_dir: samples/${general.name}/count_2_length_disabled/seed_${train.seed}
